### ISSUE TITLE
WebUSB "Failed to connect to device"

### ISSUE THREAD

**Issue by ShawnHymel** [edgeimpulse/firmware-espressif-esp32#2]
When I first plug in the ESP-EYE (running the latest Edge Impulse firmware), I will often get the following error when trying to connect via WebUSB from a project: "Failed to connect to device."

![esp32-error-02](https://user-images.githubusercontent.com/5232145/171263678-5b899a4c-bb6b-415d-9795-9349b313e016.png)

Refreshing the page or unplugging/replugging the device in seems to eventually correct the issue.

**Comment by AIWintermuteAI** [comment]
Cannot reproduce the issue with Chrome 103.0.5060.114 (Official Build) (x86_64) running on MacOS 12.4. Connection works every time, albeit the image transfer is a bit slow (I think web serial does not use maximum baud rate, unlike CLI). Are you still experiencing the issue?

**Comment by ShawnHymel** [comment]
@AIWintermuteAI Yes, it is still happening.

Windows 10 x64
Chrome 103.0.5060.114

I'm using the firmware here: https://cdn.edgeimpulse.com/build-system/firmware/espressif-esp32.zip (it's the one linked under the ["2. Update the firmware" step in the guide](https://docs.edgeimpulse.com/docs/development-platforms/officially-supported-mcu-targets/espressif-esp32#2.-update-the-firmware). Is that the correct firmware to use?

**Comment by AIWintermuteAI** [comment]
Hmmm, I compiled a fresh one. I'll try again tomorrow with the one from CDN.

**Comment by AIWintermuteAI** [comment]
Cannot reproduce the issue on Mac, even with firmware from CDN.

**Comment by AIWintermuteAI** [comment]
Okay, the issue is reproducible on Windows 10, Chrome Version 103.0.5060.114 (Official Build) (64-bit). 
For me, it always fails to connect the first time, but always succeeds after refresh of the page. 
I think the source of the issue is somewhere within mechanism how device connection works with Web USB - I noticed other Windows users had similar problems with Wio Terminal. Perhaps something as simple as upping timeout can fix the issue.
I'd advice to create an issue in our internal repository, since I do not think it is firmware specific (can connect normally with CLI and other OS).
